### ISSUE TITLE
StickerCommand

### ISSUE THREAD

**Issue by LeoAl1590** [emreyigitcbc/ecwhatbot#1]
Hi, i'm trying to create a sticker with the command, but I get this:

```
(node:3592) UnhandledPromiseRejectionWarning: ReferenceError: lang is not defined
    at Object.sendSticker (D:\Descarga\ecwhatbot-3.5\ecwhatbot-3.5\Commands\StickerCommand.js:69:16)
    at Object.run (D:\Descarga\ecwhatbot-3.5\ecwhatbot-3.5\Commands\StickerCommand.js:63:8)
    at D:\Descarga\ecwhatbot-3.5\ecwhatbot-3.5\Events\onCommand.js:32:12
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
```
I've looking around, but I don't notice anything wrong. Hope you can help me

**Comment by emreyigitcbc** [comment]
I forgot to send `lang` object to sendSticker function. I fixed it and released 3.5.1. Thanks for attention!
